services:
  #--------------------------------------------------
  # Redis pour développement local
  #--------------------------------------------------
  redis:
    image: redis:7-alpine
    container_name: redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-dev-data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru

  #--------------------------------------------------
  # Redis Commander (Interface Web) - Optionnel
  #--------------------------------------------------
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander-dev
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=admin
      - HTTP_PASSWORD=secret
    depends_on:
      - redis

volumes:
  redis-dev-data:
    name: redis-dev-data